blank_issues_enabled: false

contact_links:
  - name: Project Documentation
    url: https://github.com/arrowcam-dev/EnterpriseEmployeeManagement/tree/main/docs
    about: Please check the documentation before opening an issue.

  - name: Architecture
    url: https://github.com/arrowcam-dev/EnterpriseEmployeeManagement/blob/main/docs/architecture.md
    about: Project Architecture
